/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockaes.h"

static const char* CMockString_aes_decrypt = "aes_decrypt";
static const char* CMockString_aes_encrypt = "aes_encrypt";
static const char* CMockString_aes_init = "aes_init";
static const char* CMockString_cipher_block = "cipher_block";
static const char* CMockString_context = "context";
static const char* CMockString_key = "key";
static const char* CMockString_keySize = "keySize";
static const char* CMockString_plain_block = "plain_block";

typedef struct _CMOCK_aes_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  cipher_context_t* Expected_context;
  const uint8_t* Expected_key;
  uint8_t Expected_keySize;

} CMOCK_aes_init_CALL_INSTANCE;

typedef struct _CMOCK_aes_encrypt_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  const cipher_context_t* Expected_context;
  const uint8_t* Expected_plain_block;
  uint8_t* Expected_cipher_block;

} CMOCK_aes_encrypt_CALL_INSTANCE;

typedef struct _CMOCK_aes_decrypt_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  const cipher_context_t* Expected_context;
  const uint8_t* Expected_cipher_block;
  uint8_t* Expected_plain_block;

} CMOCK_aes_decrypt_CALL_INSTANCE;

static struct MockaesInstance
{
  CMOCK_MEM_INDEX_TYPE aes_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE aes_encrypt_CallInstance;
  CMOCK_MEM_INDEX_TYPE aes_decrypt_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockaes_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_aes_init);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.aes_init_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_aes_encrypt);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.aes_encrypt_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_aes_decrypt);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.aes_decrypt_CallInstance, cmock_line, CMockStringCalledLess);
}

void Mockaes_Init(void)
{
  Mockaes_Destroy();
}

void Mockaes_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int aes_init(cipher_context_t* context, const uint8_t* key, uint8_t keySize)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_aes_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_aes_init);
  cmock_call_instance = (CMOCK_aes_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.aes_init_CallInstance);
  Mock.aes_init_CallInstance = CMock_Guts_MemNext(Mock.aes_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_aes_init,CMockString_context);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_context), (void*)(context), sizeof(cipher_context_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_aes_init,CMockString_key);
    if (cmock_call_instance->Expected_key == NULL)
      { UNITY_TEST_ASSERT_NULL(key, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_key, key, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_aes_init,CMockString_keySize);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_keySize, keySize, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_aes_init(CMOCK_aes_init_CALL_INSTANCE* cmock_call_instance, cipher_context_t* context, const uint8_t* key, uint8_t keySize)
{
  cmock_call_instance->Expected_context = context;
  cmock_call_instance->Expected_key = key;
  cmock_call_instance->Expected_keySize = keySize;
}

void aes_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cipher_context_t* context, const uint8_t* key, uint8_t keySize, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_aes_init_CALL_INSTANCE));
  CMOCK_aes_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_aes_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.aes_init_CallInstance = CMock_Guts_MemChain(Mock.aes_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_aes_init(cmock_call_instance, context, key, keySize);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

int aes_encrypt(const cipher_context_t* context, const uint8_t* plain_block, uint8_t* cipher_block)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_aes_encrypt_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_aes_encrypt);
  cmock_call_instance = (CMOCK_aes_encrypt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.aes_encrypt_CallInstance);
  Mock.aes_encrypt_CallInstance = CMock_Guts_MemNext(Mock.aes_encrypt_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_aes_encrypt,CMockString_context);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_context), (void*)(context), sizeof(const cipher_context_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_aes_encrypt,CMockString_plain_block);
    if (cmock_call_instance->Expected_plain_block == NULL)
      { UNITY_TEST_ASSERT_NULL(plain_block, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_plain_block, plain_block, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_aes_encrypt,CMockString_cipher_block);
    if (cmock_call_instance->Expected_cipher_block == NULL)
      { UNITY_TEST_ASSERT_NULL(cipher_block, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_cipher_block, cipher_block, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_aes_encrypt(CMOCK_aes_encrypt_CALL_INSTANCE* cmock_call_instance, const cipher_context_t* context, const uint8_t* plain_block, uint8_t* cipher_block)
{
  cmock_call_instance->Expected_context = context;
  cmock_call_instance->Expected_plain_block = plain_block;
  cmock_call_instance->Expected_cipher_block = cipher_block;
}

void aes_encrypt_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cipher_context_t* context, const uint8_t* plain_block, uint8_t* cipher_block, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_aes_encrypt_CALL_INSTANCE));
  CMOCK_aes_encrypt_CALL_INSTANCE* cmock_call_instance = (CMOCK_aes_encrypt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.aes_encrypt_CallInstance = CMock_Guts_MemChain(Mock.aes_encrypt_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_aes_encrypt(cmock_call_instance, context, plain_block, cipher_block);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

int aes_decrypt(const cipher_context_t* context, const uint8_t* cipher_block, uint8_t* plain_block)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_aes_decrypt_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_aes_decrypt);
  cmock_call_instance = (CMOCK_aes_decrypt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.aes_decrypt_CallInstance);
  Mock.aes_decrypt_CallInstance = CMock_Guts_MemNext(Mock.aes_decrypt_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_aes_decrypt,CMockString_context);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_context), (void*)(context), sizeof(const cipher_context_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_aes_decrypt,CMockString_cipher_block);
    if (cmock_call_instance->Expected_cipher_block == NULL)
      { UNITY_TEST_ASSERT_NULL(cipher_block, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_cipher_block, cipher_block, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_aes_decrypt,CMockString_plain_block);
    if (cmock_call_instance->Expected_plain_block == NULL)
      { UNITY_TEST_ASSERT_NULL(plain_block, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_plain_block, plain_block, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_aes_decrypt(CMOCK_aes_decrypt_CALL_INSTANCE* cmock_call_instance, const cipher_context_t* context, const uint8_t* cipher_block, uint8_t* plain_block)
{
  cmock_call_instance->Expected_context = context;
  cmock_call_instance->Expected_cipher_block = cipher_block;
  cmock_call_instance->Expected_plain_block = plain_block;
}

void aes_decrypt_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cipher_context_t* context, const uint8_t* cipher_block, uint8_t* plain_block, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_aes_decrypt_CALL_INSTANCE));
  CMOCK_aes_decrypt_CALL_INSTANCE* cmock_call_instance = (CMOCK_aes_decrypt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.aes_decrypt_CallInstance = CMock_Guts_MemChain(Mock.aes_decrypt_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_aes_decrypt(cmock_call_instance, context, cipher_block, plain_block);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

