/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKCBOR_H
#define _MOCKCBOR_H

#include "cbor.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockcbor_Init(void);
void Mockcbor_Destroy(void);
void Mockcbor_Verify(void);




#define cbor_init_Expect(stream, buffer, size) cbor_init_CMockExpect(__LINE__, stream, buffer, size)
void cbor_init_CMockExpect(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, unsigned char* buffer, size_t size);
#define cbor_clear_Expect(stream) cbor_clear_CMockExpect(__LINE__, stream)
void cbor_clear_CMockExpect(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream);
#define cbor_destroy_Expect(stream) cbor_destroy_CMockExpect(__LINE__, stream)
void cbor_destroy_CMockExpect(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream);
#define cbor_stream_print_Expect(stream) cbor_stream_print_CMockExpect(__LINE__, stream)
void cbor_stream_print_CMockExpect(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream);
#define cbor_stream_decode_Expect(stream) cbor_stream_decode_CMockExpect(__LINE__, stream)
void cbor_stream_decode_CMockExpect(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream);
#define cbor_serialize_int_ExpectAndReturn(stream, val, cmock_retval) cbor_serialize_int_CMockExpectAndReturn(__LINE__, stream, val, cmock_retval)
void cbor_serialize_int_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, int val, size_t cmock_to_return);
#define cbor_deserialize_int_ExpectAndReturn(stream, offset, val, cmock_retval) cbor_deserialize_int_CMockExpectAndReturn(__LINE__, stream, offset, val, cmock_retval)
void cbor_deserialize_int_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, int* val, size_t cmock_to_return);
#define cbor_serialize_uint64_t_ExpectAndReturn(stream, val, cmock_retval) cbor_serialize_uint64_t_CMockExpectAndReturn(__LINE__, stream, val, cmock_retval)
void cbor_serialize_uint64_t_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, uint64_t val, size_t cmock_to_return);
#define cbor_deserialize_uint64_t_ExpectAndReturn(stream, offset, val, cmock_retval) cbor_deserialize_uint64_t_CMockExpectAndReturn(__LINE__, stream, offset, val, cmock_retval)
void cbor_deserialize_uint64_t_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, uint64_t* val, size_t cmock_to_return);
#define cbor_serialize_int64_t_ExpectAndReturn(stream, val, cmock_retval) cbor_serialize_int64_t_CMockExpectAndReturn(__LINE__, stream, val, cmock_retval)
void cbor_serialize_int64_t_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, int64_t val, size_t cmock_to_return);
#define cbor_deserialize_int64_t_ExpectAndReturn(stream, offset, val, cmock_retval) cbor_deserialize_int64_t_CMockExpectAndReturn(__LINE__, stream, offset, val, cmock_retval)
void cbor_deserialize_int64_t_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, int64_t* val, size_t cmock_to_return);
#define cbor_serialize_bool_ExpectAndReturn(stream, val, cmock_retval) cbor_serialize_bool_CMockExpectAndReturn(__LINE__, stream, val, cmock_retval)
void cbor_serialize_bool_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, bool val, size_t cmock_to_return);
#define cbor_deserialize_bool_ExpectAndReturn(stream, offset, val, cmock_retval) cbor_deserialize_bool_CMockExpectAndReturn(__LINE__, stream, offset, val, cmock_retval)
void cbor_deserialize_bool_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, bool* val, size_t cmock_to_return);
#define cbor_serialize_float_half_ExpectAndReturn(stream, val, cmock_retval) cbor_serialize_float_half_CMockExpectAndReturn(__LINE__, stream, val, cmock_retval)
void cbor_serialize_float_half_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, float val, size_t cmock_to_return);
#define cbor_deserialize_float_half_ExpectAndReturn(stream, offset, val, cmock_retval) cbor_deserialize_float_half_CMockExpectAndReturn(__LINE__, stream, offset, val, cmock_retval)
void cbor_deserialize_float_half_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, float* val, size_t cmock_to_return);
#define cbor_serialize_float_ExpectAndReturn(stream, val, cmock_retval) cbor_serialize_float_CMockExpectAndReturn(__LINE__, stream, val, cmock_retval)
void cbor_serialize_float_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, float val, size_t cmock_to_return);
#define cbor_deserialize_float_ExpectAndReturn(stream, offset, val, cmock_retval) cbor_deserialize_float_CMockExpectAndReturn(__LINE__, stream, offset, val, cmock_retval)
void cbor_deserialize_float_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, float* val, size_t cmock_to_return);
#define cbor_serialize_double_ExpectAndReturn(stream, val, cmock_retval) cbor_serialize_double_CMockExpectAndReturn(__LINE__, stream, val, cmock_retval)
void cbor_serialize_double_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, double val, size_t cmock_to_return);
#define cbor_deserialize_double_ExpectAndReturn(stream, offset, val, cmock_retval) cbor_deserialize_double_CMockExpectAndReturn(__LINE__, stream, offset, val, cmock_retval)
void cbor_deserialize_double_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, double* val, size_t cmock_to_return);
#define cbor_serialize_byte_string_ExpectAndReturn(stream, val, cmock_retval) cbor_serialize_byte_string_CMockExpectAndReturn(__LINE__, stream, val, cmock_retval)
void cbor_serialize_byte_string_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, const char* val, size_t cmock_to_return);
#define cbor_serialize_byte_stringl_ExpectAndReturn(stream, val, length, cmock_retval) cbor_serialize_byte_stringl_CMockExpectAndReturn(__LINE__, stream, val, length, cmock_retval)
void cbor_serialize_byte_stringl_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, const char* val, size_t length, size_t cmock_to_return);
#define cbor_deserialize_byte_string_ExpectAndReturn(stream, offset, val, length, cmock_retval) cbor_deserialize_byte_string_CMockExpectAndReturn(__LINE__, stream, offset, val, length, cmock_retval)
void cbor_deserialize_byte_string_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, char* val, size_t length, size_t cmock_to_return);
#define cbor_serialize_unicode_string_ExpectAndReturn(stream, val, cmock_retval) cbor_serialize_unicode_string_CMockExpectAndReturn(__LINE__, stream, val, cmock_retval)
void cbor_serialize_unicode_string_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, const char* val, size_t cmock_to_return);
#define cbor_deserialize_byte_string_no_copy_ExpectAndReturn(stream, offset, val, length, cmock_retval) cbor_deserialize_byte_string_no_copy_CMockExpectAndReturn(__LINE__, stream, offset, val, length, cmock_retval)
void cbor_deserialize_byte_string_no_copy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, unsigned char** val, size_t* length, size_t cmock_to_return);
#define cbor_deserialize_unicode_string_no_copy_ExpectAndReturn(stream, offset, val, length, cmock_retval) cbor_deserialize_unicode_string_no_copy_CMockExpectAndReturn(__LINE__, stream, offset, val, length, cmock_retval)
void cbor_deserialize_unicode_string_no_copy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, unsigned char** val, size_t* length, size_t cmock_to_return);
#define cbor_deserialize_unicode_string_ExpectAndReturn(stream, offset, val, length, cmock_retval) cbor_deserialize_unicode_string_CMockExpectAndReturn(__LINE__, stream, offset, val, length, cmock_retval)
void cbor_deserialize_unicode_string_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, char* val, size_t length, size_t cmock_to_return);
#define cbor_serialize_array_ExpectAndReturn(stream, array_length, cmock_retval) cbor_serialize_array_CMockExpectAndReturn(__LINE__, stream, array_length, cmock_retval)
void cbor_serialize_array_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, size_t array_length, size_t cmock_to_return);
#define cbor_deserialize_array_ExpectAndReturn(stream, offset, array_length, cmock_retval) cbor_deserialize_array_CMockExpectAndReturn(__LINE__, stream, offset, array_length, cmock_retval)
void cbor_deserialize_array_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, size_t* array_length, size_t cmock_to_return);
#define cbor_serialize_array_indefinite_ExpectAndReturn(stream, cmock_retval) cbor_serialize_array_indefinite_CMockExpectAndReturn(__LINE__, stream, cmock_retval)
void cbor_serialize_array_indefinite_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, size_t cmock_to_return);
#define cbor_deserialize_array_indefinite_ExpectAndReturn(stream, offset, cmock_retval) cbor_deserialize_array_indefinite_CMockExpectAndReturn(__LINE__, stream, offset, cmock_retval)
void cbor_deserialize_array_indefinite_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, size_t cmock_to_return);
#define cbor_serialize_map_ExpectAndReturn(stream, map_length, cmock_retval) cbor_serialize_map_CMockExpectAndReturn(__LINE__, stream, map_length, cmock_retval)
void cbor_serialize_map_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, size_t map_length, size_t cmock_to_return);
#define cbor_deserialize_map_ExpectAndReturn(stream, offset, map_length, cmock_retval) cbor_deserialize_map_CMockExpectAndReturn(__LINE__, stream, offset, map_length, cmock_retval)
void cbor_deserialize_map_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, size_t* map_length, size_t cmock_to_return);
#define cbor_serialize_map_indefinite_ExpectAndReturn(stream, cmock_retval) cbor_serialize_map_indefinite_CMockExpectAndReturn(__LINE__, stream, cmock_retval)
void cbor_serialize_map_indefinite_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, size_t cmock_to_return);
#define cbor_deserialize_map_indefinite_ExpectAndReturn(stream, offset, cmock_retval) cbor_deserialize_map_indefinite_CMockExpectAndReturn(__LINE__, stream, offset, cmock_retval)
void cbor_deserialize_map_indefinite_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, size_t cmock_to_return);
#define cbor_serialize_date_time_ExpectAndReturn(stream, val, cmock_retval) cbor_serialize_date_time_CMockExpectAndReturn(__LINE__, stream, val, cmock_retval)
void cbor_serialize_date_time_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, struct tm* val, size_t cmock_to_return);
#define cbor_deserialize_date_time_ExpectAndReturn(stream, offset, val, cmock_retval) cbor_deserialize_date_time_CMockExpectAndReturn(__LINE__, stream, offset, val, cmock_retval)
void cbor_deserialize_date_time_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, struct tm* val, size_t cmock_to_return);
#define cbor_serialize_date_time_epoch_ExpectAndReturn(stream, val, cmock_retval) cbor_serialize_date_time_epoch_CMockExpectAndReturn(__LINE__, stream, val, cmock_retval)
void cbor_serialize_date_time_epoch_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, time_t val, size_t cmock_to_return);
#define cbor_deserialize_date_time_epoch_ExpectAndReturn(stream, offset, val, cmock_retval) cbor_deserialize_date_time_epoch_CMockExpectAndReturn(__LINE__, stream, offset, val, cmock_retval)
void cbor_deserialize_date_time_epoch_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, time_t* val, size_t cmock_to_return);
#define cbor_write_tag_ExpectAndReturn(stream, tag, cmock_retval) cbor_write_tag_CMockExpectAndReturn(__LINE__, stream, tag, cmock_retval)
void cbor_write_tag_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, unsigned char tag, size_t cmock_to_return);
#define cbor_at_tag_ExpectAndReturn(stream, offset, cmock_retval) cbor_at_tag_CMockExpectAndReturn(__LINE__, stream, offset, cmock_retval)
void cbor_at_tag_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, bool cmock_to_return);
#define cbor_write_break_ExpectAndReturn(stream, cmock_retval) cbor_write_break_CMockExpectAndReturn(__LINE__, stream, cmock_retval)
void cbor_write_break_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, cbor_stream_t* stream, size_t cmock_to_return);
#define cbor_at_break_ExpectAndReturn(stream, offset, cmock_retval) cbor_at_break_CMockExpectAndReturn(__LINE__, stream, offset, cmock_retval)
void cbor_at_break_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, bool cmock_to_return);
#define cbor_at_end_ExpectAndReturn(stream, offset, cmock_retval) cbor_at_end_CMockExpectAndReturn(__LINE__, stream, offset, cmock_retval)
void cbor_at_end_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const cbor_stream_t* stream, size_t offset, bool cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
